# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/lab4_design_lab4_ip_0_6.xci
# IP: The module: 'lab4_design_lab4_ip_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz_ooc.xdc

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/lab4_design_lab4_ip_0_6.xci
# IP: The module: 'lab4_design_lab4_ip_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_lab4_ip_0_6/src/audio_clk_wiz_1/audio_clk_wiz_ooc.xdc
