# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5.xci
# IP: The module: 'lab4_design_rst_clk_wiz_1_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5.xci
# IP: The module: 'lab4_design_rst_clk_wiz_1_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_design_rst_clk_wiz_1_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
