# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_lab4_ip_0_1/skrach_design_lab4_ip_0_1.xci
# IP: The module: 'skrach_design_lab4_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz_ooc.xdc

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_lab4_ip_0_1/skrach_design_lab4_ip_0_1.xci
# IP: The module: 'skrach_design_lab4_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==audio_clk_wiz || ORIG_REF_NAME==audio_clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz_ooc.xdc
