# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/docquantum/homework/skrach_core/skrach_core.cache/wt [current_project]
set_property parent.project_path /home/docquantum/homework/skrach_core/skrach_core.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/docquantum/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths /home/docquantum/homework/ce446_solovey/ip_repo/skrach_core_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/docquantum/homework/skrach_core/skrach_core.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/skrach_core.srcs/audio_init.v
read_vhdl -library xil_defaultlib {
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/skrach_core.srcs/TWICtl.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/skrach_core.srcs/audio_codec_wrapper.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/counter.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/skrach_core.srcs/i2s_ctl.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/skrach_parts.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/oscillator.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/adsr.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/src/Sync_ff.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/mixer.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/operator.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/skrach_core.vhd
  /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/imports/src/rst_sync.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/new/test.vhd
read_ip -quiet /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/skrach_core/skrach_core.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/docquantum/homework/skrach_core/skrach_core.srcs/constrs_1/imports/skrach_core.srcs/skrach_core.xdc
set_property used_in_implementation false [get_files /home/docquantum/homework/skrach_core/skrach_core.srcs/constrs_1/imports/skrach_core.srcs/skrach_core.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
