# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/lab4.xdc

# Block Designs: bd/lab4_design/lab4_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design || ORIG_REF_NAME==lab4_design} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_microblaze_0_5/lab4_design_microblaze_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_microblaze_0_5 || ORIG_REF_NAME==lab4_design_microblaze_0_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_dlmb_v10_5/lab4_design_dlmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_dlmb_v10_5 || ORIG_REF_NAME==lab4_design_dlmb_v10_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_ilmb_v10_5/lab4_design_ilmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_ilmb_v10_5 || ORIG_REF_NAME==lab4_design_ilmb_v10_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_dlmb_bram_if_cntlr_5/lab4_design_dlmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_dlmb_bram_if_cntlr_5 || ORIG_REF_NAME==lab4_design_dlmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_ilmb_bram_if_cntlr_5/lab4_design_ilmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_ilmb_bram_if_cntlr_5 || ORIG_REF_NAME==lab4_design_ilmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_lmb_bram_5/lab4_design_lmb_bram_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_lmb_bram_5 || ORIG_REF_NAME==lab4_design_lmb_bram_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_mdm_1_5/lab4_design_mdm_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_mdm_1_5 || ORIG_REF_NAME==lab4_design_mdm_1_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_clk_wiz_1_5/lab4_design_clk_wiz_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_clk_wiz_1_5 || ORIG_REF_NAME==lab4_design_clk_wiz_1_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_rst_clk_wiz_1_100M_5/lab4_design_rst_clk_wiz_1_100M_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_rst_clk_wiz_1_100M_5 || ORIG_REF_NAME==lab4_design_rst_clk_wiz_1_100M_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_axi_uartlite_0_5/lab4_design_axi_uartlite_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_axi_uartlite_0_5 || ORIG_REF_NAME==lab4_design_axi_uartlite_0_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_xbar_5/lab4_design_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_xbar_5 || ORIG_REF_NAME==lab4_design_xbar_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_microblaze_0_axi_periph_5/lab4_design_microblaze_0_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_microblaze_0_axi_periph_5 || ORIG_REF_NAME==lab4_design_microblaze_0_axi_periph_5} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_mig_7series_0_7/lab4_design_mig_7series_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_mig_7series_0_7 || ORIG_REF_NAME==lab4_design_mig_7series_0_7} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_rst_mig_7series_0_100M_6/lab4_design_rst_mig_7series_0_100M_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_rst_mig_7series_0_100M_6 || ORIG_REF_NAME==lab4_design_rst_mig_7series_0_100M_6} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_lab4_ip_0_6/lab4_design_lab4_ip_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_lab4_ip_0_6 || ORIG_REF_NAME==lab4_design_lab4_ip_0_6} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_axi_uartlite_1_3/lab4_design_axi_uartlite_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_axi_uartlite_1_3 || ORIG_REF_NAME==lab4_design_axi_uartlite_1_3} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_auto_cc_0/lab4_design_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_auto_cc_0 || ORIG_REF_NAME==lab4_design_auto_cc_0} -quiet] -quiet

# IP: bd/lab4_design/ip/lab4_design_auto_pc_0/lab4_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_design_auto_pc_0 || ORIG_REF_NAME==lab4_design_auto_pc_0} -quiet] -quiet

# XDC: bd/lab4_design/lab4_design_ooc.xdc
