# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/docquantum/homework/ce446_solovey/final/code/Skrach.cache/wt [current_project]
set_property parent.project_path /home/docquantum/homework/ce446_solovey/final/code/Skrach.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/docquantum/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/docquantum/homework/ce446_solovey/final/code/ip_repo/axi_uartlite_v2_1
  /home/docquantum/homework/ce446_solovey/lab/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/docquantum/homework/ce446_solovey/final/code/Skrach.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/hdl/skrach_design_wrapper.vhd
add_files /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/skrach_design.bd
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_microblaze_0_3/skrach_design_microblaze_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_microblaze_0_3/skrach_design_microblaze_0_3_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_microblaze_0_3/skrach_design_microblaze_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_dlmb_v10_3/skrach_design_dlmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_dlmb_v10_3/skrach_design_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_ilmb_v10_3/skrach_design_ilmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_ilmb_v10_3/skrach_design_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_dlmb_bram_if_cntlr_3/skrach_design_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_ilmb_bram_if_cntlr_3/skrach_design_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_lmb_bram_3/skrach_design_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_mdm_1_3/skrach_design_mdm_1_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_mdm_1_3/skrach_design_mdm_1_3_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_clk_wiz_1_3/skrach_design_clk_wiz_1_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_clk_wiz_1_3/skrach_design_clk_wiz_1_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_clk_wiz_1_3/skrach_design_clk_wiz_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_clk_wiz_1_100M_3/skrach_design_rst_clk_wiz_1_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_clk_wiz_1_100M_3/skrach_design_rst_clk_wiz_1_100M_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_clk_wiz_1_100M_3/skrach_design_rst_clk_wiz_1_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_0_3/skrach_design_axi_uartlite_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_0_3/skrach_design_axi_uartlite_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_0_3/skrach_design_axi_uartlite_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_xbar_3/skrach_design_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_mig_7series_0_3/skrach_design_mig_7series_0_3/user_design/constraints/skrach_design_mig_7series_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_mig_7series_0_3/skrach_design_mig_7series_0_3/user_design/constraints/skrach_design_mig_7series_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_mig_7series_0_3/skrach_design_mig_7series_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_1/bd_cd63_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_1/bd_cd63_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_2/bd_cd63_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_2/bd_cd63_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_3/bd_cd63_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_3/bd_cd63_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_4/bd_cd63_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_5/bd_cd63_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_6/bd_cd63_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_7/bd_cd63_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_8/bd_cd63_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_12/bd_cd63_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_13/bd_cd63_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_14/bd_cd63_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_15/bd_cd63_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_16/bd_cd63_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_17/bd_cd63_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_21/bd_cd63_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_22/bd_cd63_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_23/bd_cd63_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_24/bd_cd63_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_25/bd_cd63_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_26/bd_cd63_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_27/bd_cd63_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_28/bd_cd63_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/bd_0/ip/ip_29/bd_cd63_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_mig_7series_0_100M_3/skrach_design_rst_mig_7series_0_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_mig_7series_0_100M_3/skrach_design_rst_mig_7series_0_100M_3.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_rst_mig_7series_0_100M_3/skrach_design_rst_mig_7series_0_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/final/code/ip_repo/audio_clk_wiz/audio_clk_wiz_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/skrach_design_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_microblaze_0_3/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/constrs_1/imports/new/lab4.xdc
set_property used_in_implementation false [get_files /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/constrs_1/imports/new/lab4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top skrach_design_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef skrach_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file skrach_design_wrapper_utilization_synth.rpt -pb skrach_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
