# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xci
# IP: The module: 'skrach_design_axi_uartlite_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xci
# IP: The module: 'skrach_design_axi_uartlite_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/docquantum/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_axi_uartlite_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
