# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/skrach.xdc

# Block Designs: bd/skrach_design/skrach_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design || ORIG_REF_NAME==skrach_design} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_microblaze_0_3/skrach_design_microblaze_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_microblaze_0_3 || ORIG_REF_NAME==skrach_design_microblaze_0_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_dlmb_v10_3/skrach_design_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_dlmb_v10_3 || ORIG_REF_NAME==skrach_design_dlmb_v10_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_ilmb_v10_3/skrach_design_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_ilmb_v10_3 || ORIG_REF_NAME==skrach_design_ilmb_v10_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_dlmb_bram_if_cntlr_3/skrach_design_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==skrach_design_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_ilmb_bram_if_cntlr_3/skrach_design_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==skrach_design_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_lmb_bram_3/skrach_design_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_lmb_bram_3 || ORIG_REF_NAME==skrach_design_lmb_bram_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_mdm_1_3/skrach_design_mdm_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_mdm_1_3 || ORIG_REF_NAME==skrach_design_mdm_1_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_rst_clk_wiz_1_100M_3/skrach_design_rst_clk_wiz_1_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==skrach_design_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_axi_uartlite_0_3/skrach_design_axi_uartlite_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_axi_uartlite_0_3 || ORIG_REF_NAME==skrach_design_axi_uartlite_0_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_axi_uartlite_1_3/skrach_design_axi_uartlite_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_axi_uartlite_1_3 || ORIG_REF_NAME==skrach_design_axi_uartlite_1_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_xbar_3/skrach_design_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_xbar_3 || ORIG_REF_NAME==skrach_design_xbar_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_microblaze_0_axi_periph_3/skrach_design_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_microblaze_0_axi_periph_3 || ORIG_REF_NAME==skrach_design_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_mig_7series_0_3/skrach_design_mig_7series_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_mig_7series_0_3 || ORIG_REF_NAME==skrach_design_mig_7series_0_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_axi_smc_0/skrach_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_axi_smc_0 || ORIG_REF_NAME==skrach_design_axi_smc_0} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_rst_mig_7series_0_100M_3/skrach_design_rst_mig_7series_0_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_rst_mig_7series_0_100M_3 || ORIG_REF_NAME==skrach_design_rst_mig_7series_0_100M_3} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_skrach_core_0_1/skrach_design_skrach_core_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_skrach_core_0_1 || ORIG_REF_NAME==skrach_design_skrach_core_0_1} -quiet] -quiet

# IP: bd/skrach_design/ip/skrach_design_clk_wiz_0_0/skrach_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==skrach_design_clk_wiz_0_0 || ORIG_REF_NAME==skrach_design_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/skrach_design/skrach_design_ooc.xdc
