# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_auto_pc_2/skrach_design_auto_pc_2.xci
# IP: The module: 'skrach_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_auto_pc_2/skrach_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_auto_pc_2/skrach_design_auto_pc_2.xci
# IP: The module: 'skrach_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/docquantum/homework/ce446_solovey/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_auto_pc_2/skrach_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
